### ISSUE TITLE
填上了手机号和密码但是一直报错

### ISSUE THREAD

**Issue by LeonX86** [kitUIN/nonebot_tools#10]
2-17 19:09:54 [ERROR] nonebot | Running matcher <Matcher from nonebot-plugin-ncm, type=message, priority=2, temp=False> failed.
Traceback (most recent call last):
  File "bot.py", line 40, in <module>
    nonebot.run(app="__mp_main__:app")
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/main.py", line 463, in run
    server.run()
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/python3/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/message.py", line 153, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/usr/local/python3/lib/python3.8/site-packages/nonebot/message.py", line 202, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 635, in simple_run
    await handler(
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot-plugin-ncm/__init__.py", line 72, in music_reply_receive
    await Ncm(bot, event).download(ids=[int(nid[1])])
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot-plugin-ncm/data_source.py", line 46, in __init__
    self.api.login.LoginViaCellphone(phone=ncm_config.ncm_phone, password=ncm_config.ncm_password)
  File "/usr/local/python3/lib/python3.8/site-packages/pyncm/apis/login.py", line 112, in LoginViaCellphone
    return LoginViaCellphone()
  File "/usr/local/python3/lib/python3.8/site-packages/pyncm/apis/login.py", line 123, in LoginViaCellphone
    WriteLoginInfo(login_status)
  File "/usr/local/python3/lib/python3.8/site-packages/pyncm/apis/login.py", line 20, in WriteLoginInfo
    raise LoginFailedException(sess.login_info['content'])
pyncm.apis.LoginFailedException: {'code': 400}

**Comment by kitUIN** [comment]
很明显，这是登陆失败...
你确定你输入的账号密码是正确的吗

**Comment by LeonX86** [comment]
> 
没输错呀QAQ是在等于号后面直接加手机号然后下面等于号后面加密码呀，没加什么特殊字符啊

**Comment by LeonX86** [comment]
试了好多次把注释删掉了居然行了啊这
